application: k-sketch-test
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /app
  static_dir: app
  expiration: 1m

- url: /test
  static_dir: test
  expiration: 1m

- url: /.*
  script: backend.application

libraries:
- name: webapp2
  version: "2.5.1"


