application: k-sketch-test
version: 15
runtime: python27
api_version: 1
threadsafe: false

builtins:
#- deferred: on

handlers:

- url: /
  static_files: index.html
  upload: index.html
  
- url: /index.html
  static_files: index.html
  upload: index.html
  
- url: /app
  static_dir: app
  expiration: 1m

- url: /test
  static_dir: test
  expiration: 1m

- url: /user/.*
  script: rpx.application

- url: /.*
  script: backend.application
  
libraries:
- name: webapp2
  version: "2.5.1"


